// <auto-generated />
namespace GBAB_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialmigrationsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialmigrationsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "202001262149273_initial-migration-setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
